; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp01

[env:esp01]
platform = espressif8266
board = esp01
framework = arduino
lib_deps = 
	Wire
	knolleary/PubSubClient@^2.8
	DHT sensor library
	adafruit/Adafruit BME680 Library@^2.0.2
	adafruit/Adafruit Unified Sensor@^1.1.13
	adafruit/Adafruit BusIO@^1.14.4
	SPI
	adafruit/Adafruit MCP9808 Library@^2.0.0
	Preferences
	ESP8266WebServer

upload_speed = 921600
monitor_speed = 19200
monitor_port = COM5
build_flags = -D BUILD_ENV_VAL=1

[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
lib_deps = 
	Wire
	knolleary/PubSubClient@^2.8
	DHT sensor library
	adafruit/Adafruit BME680 Library@^2.0.2
	adafruit/Adafruit Unified Sensor@^1.1.13
	adafruit/Adafruit BusIO@^1.14.4
	SPI
	adafruit/Adafruit MCP9808 Library@^2.0.0
	Preferences
	ESP8266WebServer

upload_speed = 921600
monitor_speed = 19200
monitor_port = COM4
build_flags = -D BUILD_ENV_VAL=2

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	Wire
	knolleary/PubSubClient@^2.8
	DHT sensor library
	adafruit/Adafruit BME680 Library@^2.0.2
	adafruit/Adafruit Unified Sensor@^1.1.13
	adafruit/Adafruit BusIO@^1.14.4
	SPI
	adafruit/Adafruit MCP9808 Library@^2.0.0
upload_speed = 921600
monitor_speed = 19200
monitor_port = COM6
build_flags = -D BUILD_ENV_VAL=3
